<?php

return [

    // ファイルアップロード許可設定
    'upload' => [
        // クライアント拡張子の許可リスト
        'allowed_extensions' => [
            '7z',
            'aac',
            'ai',
            'avi',
            'avif',
            'bmp',
            'csv',
            'doc',
            'docx',
            'gif',
            'gz',
            'jpeg',
            'jpg',
            'json',
            'md',
            'mov',
            'mp3',
            'mp4',
            'odp',
            'ods',
            'odt',
            'ogg',
            'pdf',
            'png',
            'ppt',
            'pptx',
            'rar',
            'rtf',
            'tar',
            'tif',
            'tiff',
            'txt',
            'wav',
            'webm',
            'webp',
            'xls',
            'xlsx',
            'xml',
            'zip',
        ],

        // 拡張子の表示カテゴリ
        'extension_categories' => [
            [
                'label' => '文書ファイル',
                'description' => '申請書や資料など、文書データをアップロードする場合に利用します。',
                'extensions' => [
                    'csv',
                    'doc',
                    'docx',
                    'json',
                    'md',
                    'odp',
                    'ods',
                    'odt',
                    'pdf',
                    'ppt',
                    'pptx',
                    'rtf',
                    'txt',
                    'xls',
                    'xlsx',
                    'xml',
                ],
            ],
            [
                'label' => '画像ファイル',
                'description' => '写真やスクリーンショットなど、画像をアップロードする場合に利用します。',
                'extensions' => [
                    'ai',
                    'avif',
                    'bmp',
                    'gif',
                    'jpeg',
                    'jpg',
                    'png',
                    'tif',
                    'tiff',
                    'webp',
                ],
            ],
            [
                'label' => '音声・動画ファイル',
                'description' => '録音データや動画データをアップロードする場合に利用します。',
                'extensions' => [
                    'aac',
                    'avi',
                    'mov',
                    'mp3',
                    'mp4',
                    'ogg',
                    'wav',
                    'webm',
                ],
            ],
            [
                'label' => '圧縮ファイル',
                'description' => '複数ファイルをまとめた圧縮データをアップロードする場合に利用します。',
                'extensions' => [
                    '7z',
                    'gz',
                    'rar',
                    'tar',
                    'zip',
                ],
            ],
        ],

        // 拡張子ごとの許可MIMEタイプ
        'mimetype_map' => [
            '7z'   => ['application/x-7z-compressed'],
            'aac'  => ['audio/aac'],
            'ai'   => ['application/postscript', 'application/illustrator'],
            'avi'  => ['video/x-msvideo'],
            'avif' => ['image/avif'],
            'bmp'  => ['image/bmp'],
            'csv'  => ['text/csv', 'application/csv', 'text/plain'],
            'doc'  => ['application/msword'],
            'docx' => ['application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
            'gif'  => ['image/gif'],
            'gz'   => ['application/gzip', 'application/x-gzip'],
            'jpeg' => ['image/jpeg'],
            'jpg'  => ['image/jpeg'],
            'json' => ['application/json', 'text/json'],
            'md'   => ['text/markdown', 'text/x-markdown', 'text/plain'],
            'mov'  => ['video/quicktime'],
            'mp3'  => ['audio/mpeg'],
            'mp4'  => ['video/mp4'],
            'odp'  => ['application/vnd.oasis.opendocument.presentation'],
            'ods'  => ['application/vnd.oasis.opendocument.spreadsheet'],
            'odt'  => ['application/vnd.oasis.opendocument.text'],
            'ogg'  => ['application/ogg', 'audio/ogg', 'video/ogg'],
            'pdf'  => ['application/pdf'],
            'png'  => ['image/png'],
            'ppt'  => ['application/vnd.ms-powerpoint'],
            'pptx' => ['application/vnd.openxmlformats-officedocument.presentationml.presentation'],
            'rar'  => ['application/vnd.rar', 'application/x-rar-compressed'],
            'rtf'  => ['application/rtf'],
            'tar'  => ['application/x-tar'],
            'tif'  => ['image/tiff'],
            'tiff' => ['image/tiff'],
            'txt'  => ['text/plain'],
            'wav'  => ['audio/wav'],
            'webm' => ['video/webm'],
            'webp' => ['image/webp'],
            'xls'  => ['application/vnd.ms-excel'],
            'xlsx' => ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],
            'xml'  => ['application/xml', 'text/xml'],
            'zip'  => ['application/zip', 'application/x-zip-compressed'],
        ],
    ],
];
