<?php

namespace App\Enums;

use App\Enums\EnumsBase;

/**
 * カラーネーム（カラーコード）
 */
final class ColorName extends EnumsBase
{
    // 定数メンバ
    const aliceblue = 'aliceblue';
    const antiquewhite = 'antiquewhite';
    const aqua = 'aqua';
    const aquamarine = 'aquamarine';
    const azure = 'azure';
    const beige = 'beige';
    const bisque = 'bisque';
    const black = 'black';
    const blanchedalmond = 'blanchedalmond';
    const blue = 'blue';
    const blueviolet = 'blueviolet';
    const brown = 'brown';
    const burlywood = 'burlywood';
    const cadetblue = 'cadetblue';
    const chartreuse = 'chartreuse';
    const chocolate = 'chocolate';
    const coral = 'coral';
    const cornflowerblue = 'cornflowerblue';
    const cornsilk = 'cornsilk';
    const crimson = 'crimson';
    const cyan = 'cyan';
    const darkblue = 'darkblue';
    const darkcyan = 'darkcyan';
    const darkgoldenrod = 'darkgoldenrod';
    const darkgray = 'darkgray';
    const darkgreen = 'darkgreen';
    const darkgrey = 'darkgrey';
    const darkkhaki = 'darkkhaki';
    const darkmagenta = 'darkmagenta';
    const darkolivegreen = 'darkolivegreen';
    const darkorange = 'darkorange';
    const darkorchid = 'darkorchid';
    const darkred = 'darkred';
    const darksalmon = 'darksalmon';
    const darkseagreen = 'darkseagreen';
    const darkslateblue = 'darkslateblue';
    const darkslategray = 'darkslategray';
    const darkslategrey = 'darkslategrey';
    const darkturquoise = 'darkturquoise';
    const darkviolet = 'darkviolet';
    const deeppink = 'deeppink';
    const deepskyblue = 'deepskyblue';
    const dimgray = 'dimgray';
    const dimgrey = 'dimgrey';
    const dodgerblue = 'dodgerblue';
    const firebrick = 'firebrick';
    const floralwhite = 'floralwhite';
    const forestgreen = 'forestgreen';
    const fuchsia = 'fuchsia';
    const gainsboro = 'gainsboro';
    const ghostwhite = 'ghostwhite';
    const gold = 'gold';
    const goldenrod = 'goldenrod';
    const gray = 'gray';
    const green = 'green';
    const greenyellow = 'greenyellow';
    const grey = 'grey';
    const honeydew = 'honeydew';
    const hotpink = 'hotpink';
    const indianred = 'indianred';
    const indigo = 'indigo';
    const ivory = 'ivory';
    const khaki = 'khaki';
    const lavender = 'lavender';
    const lavenderblush = 'lavenderblush';
    const lawngreen = 'lawngreen';
    const lemonchiffon = 'lemonchiffon';
    const lightblue = 'lightblue';
    const lightcoral = 'lightcoral';
    const lightcyan = 'lightcyan';
    const lightgoldenrodyellow = 'lightgoldenrodyellow';
    const lightgray = 'lightgray';
    const lightgreen = 'lightgreen';
    const lightgrey = 'lightgrey';
    const lightpink = 'lightpink';
    const lightsalmon = 'lightsalmon';
    const lightseagreen = 'lightseagreen';
    const lightskyblue = 'lightskyblue';
    const lightslategray = 'lightslategray';
    const lightslategrey = 'lightslategrey';
    const lightsteelblue = 'lightsteelblue';
    const lightyellow = 'lightyellow';
    const lime = 'lime';
    const limegreen = 'limegreen';
    const linen = 'linen';
    const magenta = 'magenta';
    const maroon = 'maroon';
    const mediumaquamarine = 'mediumaquamarine';
    const mediumblue = 'mediumblue';
    const mediumorchid = 'mediumorchid';
    const mediumpurple = 'mediumpurple';
    const mediumseagreen = 'mediumseagreen';
    const mediumslateblue = 'mediumslateblue';
    const mediumspringgreen = 'mediumspringgreen';
    const mediumturquoise = 'mediumturquoise';
    const mediumvioletred = 'mediumvioletred';
    const midnightblue = 'midnightblue';
    const mintcream = 'mintcream';
    const mistyrose = 'mistyrose';
    const moccasin = 'moccasin';
    const navajowhite = 'navajowhite';
    const navy = 'navy';
    const oldlace = 'oldlace';
    const olive = 'olive';
    const olivedrab = 'olivedrab';
    const orange = 'orange';
    const orangered = 'orangered';
    const orchid = 'orchid';
    const palegoldenrod = 'palegoldenrod';
    const palegreen = 'palegreen';
    const paleturquoise = 'paleturquoise';
    const palevioletred = 'palevioletred';
    const papayawhip = 'papayawhip';
    const peachpuff = 'peachpuff';
    const peru = 'peru';
    const pink = 'pink';
    const plum = 'plum';
    const powderblue = 'powderblue';
    const purple = 'purple';
    const rebeccapurple = 'rebeccapurple';
    const red = 'red';
    const rosybrown = 'rosybrown';
    const royalblue = 'royalblue';
    const saddlebrown = 'saddlebrown';
    const salmon = 'salmon';
    const sandybrown = 'sandybrown';
    const seagreen = 'seagreen';
    const seashell = 'seashell';
    const sienna = 'sienna';
    const silver = 'silver';
    const skyblue = 'skyblue';
    const slateblue = 'slateblue';
    const slategray = 'slategray';
    const slategrey = 'slategrey';
    const snow = 'snow';
    const springgreen = 'springgreen';
    const steelblue = 'steelblue';
    const tan = 'tan';
    const teal = 'teal';
    const thistle = 'thistle';
    const tomato = 'tomato';
    const turquoise = 'turquoise';
    const violet = 'violet';
    const wheat = 'wheat';
    const white = 'white';
    const whitesmoke = 'whitesmoke';
    const yellow = 'yellow';
    const yellowgreen = 'yellowgreen';

    // key/valueの連想配列
    const enum = [
        self::aliceblue => '#F0F8FF',
        self::antiquewhite => '#FAEBD7',
        self::aqua => '#00FFFF',
        self::aquamarine => '#7FFFD4',
        self::azure => '#F0FFFF',
        self::beige => '#F5F5DC',
        self::bisque => '#FFE4C4',
        self::black => '#000000',
        self::blanchedalmond => '#FFEBCD',
        self::blue => '#0000FF',
        self::blueviolet => '#8A2BE2',
        self::brown => '#A52A2A',
        self::burlywood => '#DEB887',
        self::cadetblue => '#5F9EA0',
        self::chartreuse => '#7FFF00',
        self::chocolate => '#D2691E',
        self::coral => '#FF7F50',
        self::cornflowerblue => '#6495ED',
        self::cornsilk => '#FFF8DC',
        self::crimson => '#DC143C',
        self::cyan => '#00FFFF',
        self::darkblue => '#00008B',
        self::darkcyan => '#008B8B',
        self::darkgoldenrod => '#B8860B',
        self::darkgray => '#A9A9A9',
        self::darkgreen => '#006400',
        self::darkgrey => '#A9A9A9',
        self::darkkhaki => '#BDB76B',
        self::darkmagenta => '#8B008B',
        self::darkolivegreen => '#556B2F',
        self::darkorange => '#FF8C00',
        self::darkorchid => '#9932CC',
        self::darkred => '#8B0000',
        self::darksalmon => '#E9967A',
        self::darkseagreen => '#8FBC8F',
        self::darkslateblue => '#483D8B',
        self::darkslategray => '#2F4F4F',
        self::darkslategrey => '#2F4F4F',
        self::darkturquoise => '#00CED1',
        self::darkviolet => '#9400D3',
        self::deeppink => '#FF1493',
        self::deepskyblue => '#00BFFF',
        self::dimgray => '#696969',
        self::dimgrey => '#696969',
        self::dodgerblue => '#1E90FF',
        self::firebrick => '#B22222',
        self::floralwhite => '#FFFAF0',
        self::forestgreen => '#228B22',
        self::fuchsia => '#FF00FF',
        self::gainsboro => '#DCDCDC',
        self::ghostwhite => '#F8F8FF',
        self::gold => '#FFD700',
        self::goldenrod => '#DAA520',
        self::gray => '#808080',
        self::green => '#008000',
        self::greenyellow => '#ADFF2F',
        self::grey => '#808080',
        self::honeydew => '#F0FFF0',
        self::hotpink => '#FF69B4',
        self::indianred => '#CD5C5C',
        self::indigo => '#4B0082',
        self::ivory => '#FFFFF0',
        self::khaki => '#F0E68C',
        self::lavender => '#E6E6FA',
        self::lavenderblush => '#FFF0F5',
        self::lawngreen => '#7CFC00',
        self::lemonchiffon => '#FFFACD',
        self::lightblue => '#ADD8E6',
        self::lightcoral => '#F08080',
        self::lightcyan => '#E0FFFF',
        self::lightgoldenrodyellow => '#FAFAD2',
        self::lightgray => '#D3D3D3',
        self::lightgreen => '#90EE90',
        self::lightgrey => '#D3D3D3',
        self::lightpink => '#FFB6C1',
        self::lightsalmon => '#FFA07A',
        self::lightseagreen => '#20B2AA',
        self::lightskyblue => '#87CEFA',
        self::lightslategray => '#778899',
        self::lightslategrey => '#778899',
        self::lightsteelblue => '#B0C4DE',
        self::lightyellow => '#FFFFE0',
        self::lime => '#00FF00',
        self::limegreen => '#32CD32',
        self::linen => '#FAF0E6',
        self::magenta => '#FF00FF',
        self::maroon => '#800000',
        self::mediumaquamarine => '#66CDAA',
        self::mediumblue => '#0000CD',
        self::mediumorchid => '#BA55D3',
        self::mediumpurple => '#9370DB',
        self::mediumseagreen => '#3CB371',
        self::mediumslateblue => '#7B68EE',
        self::mediumspringgreen => '#00FA9A',
        self::mediumturquoise => '#48D1CC',
        self::mediumvioletred => '#C71585',
        self::midnightblue => '#191970',
        self::mintcream => '#F5FFFA',
        self::mistyrose => '#FFE4E1',
        self::moccasin => '#FFE4B5',
        self::navajowhite => '#FFDEAD',
        self::navy => '#000080',
        self::oldlace => '#FDF5E6',
        self::olive => '#808000',
        self::olivedrab => '#6B8E23',
        self::orange => '#FFA500',
        self::orangered => '#FF4500',
        self::orchid => '#DA70D6',
        self::palegoldenrod => '#EEE8AA',
        self::palegreen => '#98FB98',
        self::paleturquoise => '#AFEEEE',
        self::palevioletred => '#DB7093',
        self::papayawhip => '#FFEFD5',
        self::peachpuff => '#FFDAB9',
        self::peru => '#CD853F',
        self::pink => '#FFC0CB',
        self::plum => '#DDA0DD',
        self::powderblue => '#B0E0E6',
        self::purple => '#800080',
        self::rebeccapurple => '#663399',
        self::red => '#FF0000',
        self::rosybrown => '#BC8F8F',
        self::royalblue => '#4169E1',
        self::saddlebrown => '#8B4513',
        self::salmon => '#FA8072',
        self::sandybrown => '#F4A460',
        self::seagreen => '#2E8B57',
        self::seashell => '#FFF5EE',
        self::sienna => '#A0522D',
        self::silver => '#C0C0C0',
        self::skyblue => '#87CEEB',
        self::slateblue => '#6A5ACD',
        self::slategray => '#708090',
        self::slategrey => '#708090',
        self::snow => '#FFFAFA',
        self::springgreen => '#00FF7F',
        self::steelblue => '#4682B4',
        self::tan => '#D2B48C',
        self::teal => '#008080',
        self::thistle => '#D8BFD8',
        self::tomato => '#FF6347',
        self::turquoise => '#40E0D0',
        self::violet => '#EE82EE',
        self::wheat => '#F5DEB3',
        self::white => '#FFFFFF',
        self::whitesmoke => '#F5F5F5',
        self::yellow => '#FFFF00',
        self::yellowgreen => '#9ACD32',
    ];
}
