<?php

namespace App\Enums;

use App\Enums\EnumsBase;

/**
 * 国名コード（ISO 3166-1）
 * ※ラテン文字3文字版
 *
 * 引用：https://ja.wikipedia.org/wiki/ISO_3166-1
 */
final class CountryCodeAlpha3 extends EnumsBase
{
    // 定数メンバ
    const not_set = null;
    const ISL = 'ISL';
    const IRL = 'IRL';
    const AZE = 'AZE';
    const AFG = 'AFG';
    const USA = 'USA';
    const VIR = 'VIR';
    const ASM = 'ASM';
    const ARE = 'ARE';
    const DZA = 'DZA';
    const ARG = 'ARG';
    const ABW = 'ABW';
    const ALB = 'ALB';
    const ARM = 'ARM';
    const AIA = 'AIA';
    const AGO = 'AGO';
    const ATG = 'ATG';
    const AND = 'AND';
    const YEM = 'YEM';
    const GBR = 'GBR';
    const IOT = 'IOT';
    const VGB = 'VGB';
    const ISR = 'ISR';
    const ITA = 'ITA';
    const IRQ = 'IRQ';
    const IRN = 'IRN';
    const IND = 'IND';
    const IDN = 'IDN';
    const WLF = 'WLF';
    const UGA = 'UGA';
    const UKR = 'UKR';
    const UZB = 'UZB';
    const URY = 'URY';
    const ECU = 'ECU';
    const EGY = 'EGY';
    const EST = 'EST';
    const SWZ = 'SWZ';
    const ETH = 'ETH';
    const ERI = 'ERI';
    const SLV = 'SLV';
    const AUS = 'AUS';
    const AUT = 'AUT';
    const ALA = 'ALA';
    const OMN = 'OMN';
    const NLD = 'NLD';
    const GHA = 'GHA';
    const CPV = 'CPV';
    const GGY = 'GGY';
    const GUY = 'GUY';
    const KAZ = 'KAZ';
    const QAT = 'QAT';
    const UMI = 'UMI';
    const CAN = 'CAN';
    const GAB = 'GAB';
    const CMR = 'CMR';
    const GMB = 'GMB';
    const KHM = 'KHM';
    const MKD = 'MKD';
    const MNP = 'MNP';
    const GIN = 'GIN';
    const GNB = 'GNB';
    const CYP = 'CYP';
    const CUB = 'CUB';
    const CUW = 'CUW';
    const GRC = 'GRC';
    const KIR = 'KIR';
    const KGZ = 'KGZ';
    const GTM = 'GTM';
    const GLP = 'GLP';
    const GUM = 'GUM';
    const KWT = 'KWT';
    const COK = 'COK';
    const GRL = 'GRL';
    const CXR = 'CXR';
    const GRD = 'GRD';
    const HRV = 'HRV';
    const CYM = 'CYM';
    const KEN = 'KEN';
    const CIV = 'CIV';
    const CCK = 'CCK';
    const CRI = 'CRI';
    const COM = 'COM';
    const COL = 'COL';
    const COG = 'COG';
    const COD = 'COD';
    const SAU = 'SAU';
    const SGS = 'SGS';
    const WSM = 'WSM';
    const STP = 'STP';
    const BLM = 'BLM';
    const ZMB = 'ZMB';
    const SPM = 'SPM';
    const SMR = 'SMR';
    const MAF = 'MAF';
    const SLE = 'SLE';
    const DJI = 'DJI';
    const GIB = 'GIB';
    const JEY = 'JEY';
    const JAM = 'JAM';
    const GEO = 'GEO';
    const SYR = 'SYR';
    const SGP = 'SGP';
    const SXM = 'SXM';
    const ZWE = 'ZWE';
    const CHE = 'CHE';
    const SWE = 'SWE';
    const SDN = 'SDN';
    const SJM = 'SJM';
    const ESP = 'ESP';
    const SUR = 'SUR';
    const LKA = 'LKA';
    const SVK = 'SVK';
    const SVN = 'SVN';
    const SYC = 'SYC';
    const GNQ = 'GNQ';
    const SEN = 'SEN';
    const SRB = 'SRB';
    const KNA = 'KNA';
    const VCT = 'VCT';
    const SHN = 'SHN';
    const LCA = 'LCA';
    const SOM = 'SOM';
    const SLB = 'SLB';
    const TCA = 'TCA';
    const THA = 'THA';
    const KOR = 'KOR';
    const TWN = 'TWN';
    const TJK = 'TJK';
    const TZA = 'TZA';
    const CZE = 'CZE';
    const TCD = 'TCD';
    const CAF = 'CAF';
    const CHN = 'CHN';
    const TUN = 'TUN';
    const PRK = 'PRK';
    const CHL = 'CHL';
    const TUV = 'TUV';
    const DNK = 'DNK';
    const DEU = 'DEU';
    const TGO = 'TGO';
    const TKL = 'TKL';
    const DOM = 'DOM';
    const DMA = 'DMA';
    const TTO = 'TTO';
    const TKM = 'TKM';
    const TUR = 'TUR';
    const TON = 'TON';
    const NGA = 'NGA';
    const NRU = 'NRU';
    const NAM = 'NAM';
    const ATA = 'ATA';
    const NIU = 'NIU';
    const NIC = 'NIC';
    const NER = 'NER';
    const JPN = 'JPN';
    const ESH = 'ESH';
    const NCL = 'NCL';
    const NZL = 'NZL';
    const NPL = 'NPL';
    const NFK = 'NFK';
    const NOR = 'NOR';
    const HMD = 'HMD';
    const BHR = 'BHR';
    const HTI = 'HTI';
    const PAK = 'PAK';
    const VAT = 'VAT';
    const PAN = 'PAN';
    const VUT = 'VUT';
    const BHS = 'BHS';
    const PNG = 'PNG';
    const BMU = 'BMU';
    const PLW = 'PLW';
    const PRY = 'PRY';
    const BRB = 'BRB';
    const PSE = 'PSE';
    const HUN = 'HUN';
    const BGD = 'BGD';
    const TLS = 'TLS';
    const PCN = 'PCN';
    const FJI = 'FJI';
    const PHL = 'PHL';
    const FIN = 'FIN';
    const BTN = 'BTN';
    const BVT = 'BVT';
    const PRI = 'PRI';
    const FRO = 'FRO';
    const FLK = 'FLK';
    const BRA = 'BRA';
    const FRA = 'FRA';
    const GUF = 'GUF';
    const PYF = 'PYF';
    const ATF = 'ATF';
    const BGR = 'BGR';
    const BFA = 'BFA';
    const BRN = 'BRN';
    const BDI = 'BDI';
    const VNM = 'VNM';
    const BEN = 'BEN';
    const VEN = 'VEN';
    const BLR = 'BLR';
    const BLZ = 'BLZ';
    const PER = 'PER';
    const BEL = 'BEL';
    const POL = 'POL';
    const BIH = 'BIH';
    const BWA = 'BWA';
    const BES = 'BES';
    const BOL = 'BOL';
    const PRT = 'PRT';
    const HKG = 'HKG';
    const HND = 'HND';
    const MHL = 'MHL';
    const MAC = 'MAC';
    const MDG = 'MDG';
    const MYT = 'MYT';
    const MWI = 'MWI';
    const MLI = 'MLI';
    const MLT = 'MLT';
    const MTQ = 'MTQ';
    const MYS = 'MYS';
    const IMN = 'IMN';
    const FSM = 'FSM';
    const ZAF = 'ZAF';
    const SSD = 'SSD';
    const MMR = 'MMR';
    const MEX = 'MEX';
    const MUS = 'MUS';
    const MRT = 'MRT';
    const MOZ = 'MOZ';
    const MCO = 'MCO';
    const MDV = 'MDV';
    const MDA = 'MDA';
    const MAR = 'MAR';
    const MNG = 'MNG';
    const MNE = 'MNE';
    const MSR = 'MSR';
    const JOR = 'JOR';
    const LAO = 'LAO';
    const LVA = 'LVA';
    const LTU = 'LTU';
    const LBY = 'LBY';
    const LIE = 'LIE';
    const LBR = 'LBR';
    const ROU = 'ROU';
    const LUX = 'LUX';
    const RWA = 'RWA';
    const LSO = 'LSO';
    const LBN = 'LBN';
    const REU = 'REU';
    const RUS = 'RUS';

    // key/valueの連想配列
    const enum = [
        self::not_set=>null,
        self::ISL=>'アイスランド',
        self::IRL=>'アイルランド',
        self::AZE=>'アゼルバイジャン',
        self::AFG=>'アフガニスタン',
        self::USA=>'アメリカ合衆国',
        self::VIR=>'アメリカ領ヴァージン諸島',
        self::ASM=>'アメリカ領サモア',
        self::ARE=>'アラブ首長国連邦',
        self::DZA=>'アルジェリア',
        self::ARG=>'アルゼンチン',
        self::ABW=>'アルバ',
        self::ALB=>'アルバニア',
        self::ARM=>'アルメニア',
        self::AIA=>'アンギラ',
        self::AGO=>'アンゴラ',
        self::ATG=>'アンティグア・バーブーダ',
        self::AND=>'アンドラ',
        self::YEM=>'イエメン',
        self::GBR=>'イギリス',
        self::IOT=>'イギリス領インド洋地域',
        self::VGB=>'イギリス領ヴァージン諸島',
        self::ISR=>'イスラエル',
        self::ITA=>'イタリア',
        self::IRQ=>'イラク',
        self::IRN=>'イラン・イスラム共和国',
        self::IND=>'インド',
        self::IDN=>'インドネシア',
        self::WLF=>'ウォリス・フツナ',
        self::UGA=>'ウガンダ',
        self::UKR=>'ウクライナ',
        self::UZB=>'ウズベキスタン',
        self::URY=>'ウルグアイ',
        self::ECU=>'エクアドル',
        self::EGY=>'エジプト',
        self::EST=>'エストニア',
        self::SWZ=>'エスワティニ',
        self::ETH=>'エチオピア',
        self::ERI=>'エリトリア',
        self::SLV=>'エルサルバドル',
        self::AUS=>'オーストラリア',
        self::AUT=>'オーストリア',
        self::ALA=>'オーランド諸島',
        self::OMN=>'オマーン',
        self::NLD=>'オランダ',
        self::GHA=>'ガーナ',
        self::CPV=>'カーボベルデ',
        self::GGY=>'ガーンジー',
        self::GUY=>'ガイアナ',
        self::KAZ=>'カザフスタン',
        self::QAT=>'カタール',
        self::UMI=>'合衆国領有小離島',
        self::CAN=>'カナダ',
        self::GAB=>'ガボン',
        self::CMR=>'カメルーン',
        self::GMB=>'ガンビア',
        self::KHM=>'カンボジア',
        self::MKD=>'北マケドニア',
        self::MNP=>'北マリアナ諸島',
        self::GIN=>'ギニア',
        self::GNB=>'ギニアビサウ',
        self::CYP=>'キプロス',
        self::CUB=>'キューバ',
        self::CUW=>'キュラソー',
        self::GRC=>'ギリシャ',
        self::KIR=>'キリバス',
        self::KGZ=>'キルギス',
        self::GTM=>'グアテマラ',
        self::GLP=>'グアドループ',
        self::GUM=>'グアム',
        self::KWT=>'クウェート',
        self::COK=>'クック諸島',
        self::GRL=>'グリーンランド',
        self::CXR=>'クリスマス島',
        self::GRD=>'グレナダ',
        self::HRV=>'クロアチア',
        self::CYM=>'ケイマン諸島',
        self::KEN=>'ケニア',
        self::CIV=>'コートジボワール',
        self::CCK=>'ココス（キーリング）諸島',
        self::CRI=>'コスタリカ',
        self::COM=>'コモロ',
        self::COL=>'コロンビア',
        self::COG=>'コンゴ共和国',
        self::COD=>'コンゴ民主共和国',
        self::SAU=>'サウジアラビア',
        self::SGS=>'サウスジョージア・サウスサンドウィッチ諸島',
        self::WSM=>'サモア',
        self::STP=>'サントメ・プリンシペ',
        self::BLM=>'サン・バルテルミー',
        self::ZMB=>'ザンビア',
        self::SPM=>'サンピエール島・ミクロン島',
        self::SMR=>'サンマリノ',
        self::MAF=>'サン・マルタン（フランス領）',
        self::SLE=>'シエラレオネ',
        self::DJI=>'ジブチ',
        self::GIB=>'ジブラルタル',
        self::JEY=>'ジャージー',
        self::JAM=>'ジャマイカ',
        self::GEO=>'ジョージア',
        self::SYR=>'シリア・アラブ共和国',
        self::SGP=>'シンガポール',
        self::SXM=>'シント・マールテン（オランダ領）',
        self::ZWE=>'ジンバブエ',
        self::CHE=>'スイス',
        self::SWE=>'スウェーデン',
        self::SDN=>'スーダン',
        self::SJM=>'スヴァールバル諸島およびヤンマイエン島',
        self::ESP=>'スペイン',
        self::SUR=>'スリナム',
        self::LKA=>'スリランカ',
        self::SVK=>'スロバキア',
        self::SVN=>'スロベニア',
        self::SYC=>'セーシェル',
        self::GNQ=>'赤道ギニア',
        self::SEN=>'セネガル',
        self::SRB=>'セルビア',
        self::KNA=>'セントクリストファー・ネイビス',
        self::VCT=>'セントビンセントおよびグレナディーン諸島',
        self::SHN=>'セントヘレナ・アセンションおよびトリスタンダクーニャ',
        self::LCA=>'セントルシア',
        self::SOM=>'ソマリア',
        self::SLB=>'ソロモン諸島',
        self::TCA=>'タークス・カイコス諸島',
        self::THA=>'タイ',
        self::KOR=>'大韓民国',
        self::TWN=>'台湾（中華民国）',
        self::TJK=>'タジキスタン',
        self::TZA=>'タンザニア',
        self::CZE=>'チェコ',
        self::TCD=>'チャド',
        self::CAF=>'中央アフリカ共和国',
        self::CHN=>'中華人民共和国',
        self::TUN=>'チュニジア',
        self::PRK=>'朝鮮民主主義人民共和国',
        self::CHL=>'チリ',
        self::TUV=>'ツバル',
        self::DNK=>'デンマーク',
        self::DEU=>'ドイツ',
        self::TGO=>'トーゴ',
        self::TKL=>'トケラウ',
        self::DOM=>'ドミニカ共和国',
        self::DMA=>'ドミニカ国',
        self::TTO=>'トリニダード・トバゴ',
        self::TKM=>'トルクメニスタン',
        self::TUR=>'トルコ',
        self::TON=>'トンガ',
        self::NGA=>'ナイジェリア',
        self::NRU=>'ナウル',
        self::NAM=>'ナミビア',
        self::ATA=>'南極',
        self::NIU=>'ニウエ',
        self::NIC=>'ニカラグア',
        self::NER=>'ニジェール',
        self::JPN=>'日本',
        self::ESH=>'西サハラ',
        self::NCL=>'ニューカレドニア',
        self::NZL=>'ニュージーランド',
        self::NPL=>'ネパール',
        self::NFK=>'ノーフォーク島',
        self::NOR=>'ノルウェー',
        self::HMD=>'ハード島とマクドナルド諸島',
        self::BHR=>'バーレーン',
        self::HTI=>'ハイチ',
        self::PAK=>'パキスタン',
        self::VAT=>'バチカン市国',
        self::PAN=>'パナマ',
        self::VUT=>'バヌアツ',
        self::BHS=>'バハマ',
        self::PNG=>'パプアニューギニア',
        self::BMU=>'バミューダ',
        self::PLW=>'パラオ',
        self::PRY=>'パラグアイ',
        self::BRB=>'バルバドス',
        self::PSE=>'パレスチナ',
        self::HUN=>'ハンガリー',
        self::BGD=>'バングラデシュ',
        self::TLS=>'東ティモール',
        self::PCN=>'ピトケアン',
        self::FJI=>'フィジー',
        self::PHL=>'フィリピン',
        self::FIN=>'フィンランド',
        self::BTN=>'ブータン',
        self::BVT=>'ブーベ島',
        self::PRI=>'プエルトリコ',
        self::FRO=>'フェロー諸島',
        self::FLK=>'フォークランド（マルビナス）諸島',
        self::BRA=>'ブラジル',
        self::FRA=>'フランス',
        self::GUF=>'フランス領ギアナ',
        self::PYF=>'フランス領ポリネシア',
        self::ATF=>'フランス領南方・南極地域',
        self::BGR=>'ブルガリア',
        self::BFA=>'ブルキナファソ',
        self::BRN=>'ブルネイ・ダルサラーム',
        self::BDI=>'ブルンジ',
        self::VNM=>'ベトナム',
        self::BEN=>'ベナン',
        self::VEN=>'ベネズエラ・ボリバル共和国',
        self::BLR=>'ベラルーシ',
        self::BLZ=>'ベリーズ',
        self::PER=>'ペルー',
        self::BEL=>'ベルギー',
        self::POL=>'ポーランド',
        self::BIH=>'ボスニア・ヘルツェゴビナ',
        self::BWA=>'ボツワナ',
        self::BES=>'ボネール、シント・ユースタティウスおよびサバ',
        self::BOL=>'ボリビア多民族国',
        self::PRT=>'ポルトガル',
        self::HKG=>'香港',
        self::HND=>'ホンジュラス',
        self::MHL=>'マーシャル諸島',
        self::MAC=>'マカオ',
        self::MDG=>'マダガスカル',
        self::MYT=>'マヨット',
        self::MWI=>'マラウイ',
        self::MLI=>'マリ',
        self::MLT=>'マルタ',
        self::MTQ=>'マルティニーク',
        self::MYS=>'マレーシア',
        self::IMN=>'マン島',
        self::FSM=>'ミクロネシア連邦',
        self::ZAF=>'南アフリカ',
        self::SSD=>'南スーダン',
        self::MMR=>'ミャンマー',
        self::MEX=>'メキシコ',
        self::MUS=>'モーリシャス',
        self::MRT=>'モーリタニア',
        self::MOZ=>'モザンビーク',
        self::MCO=>'モナコ',
        self::MDV=>'モルディブ',
        self::MDA=>'モルドバ共和国',
        self::MAR=>'モロッコ',
        self::MNG=>'モンゴル',
        self::MNE=>'モンテネグロ',
        self::MSR=>'モントセラト',
        self::JOR=>'ヨルダン',
        self::LAO=>'ラオス人民民主共和国',
        self::LVA=>'ラトビア',
        self::LTU=>'リトアニア',
        self::LBY=>'リビア',
        self::LIE=>'リヒテンシュタイン',
        self::LBR=>'リベリア',
        self::ROU=>'ルーマニア',
        self::LUX=>'ルクセンブルク',
        self::RWA=>'ルワンダ',
        self::LSO=>'レソト',
        self::LBN=>'レバノン',
        self::REU=>'レユニオン',
        self::RUS=>'ロシア連邦',
    ];
}
