name: PHPCS check

on:
  push:
    branches:
      - master
    paths:
      - '**.php'
      - '!bootstrap/**'
      - '!config/**'
      - '!database/**'
      - '!node_modules/**'
      - '!routes/**'
      - '!resources/**'
      - '!storage/**'
      - '!vendor/**'
      - '!server.php'
      - '!app/Console/Kernel.php'
      - '!tests/CreatesApplication.php'
  pull_request:
  workflow_dispatch:

env:
  PHP_VERSION: '7.3'

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout (official)
      - uses: actions/checkout@v4

      # https://github.com/shivammathur/setup-php (community)
      - name: Setup PHP ${{ env.PHP_VERSION }} with cs2pr
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none
          tools: composer, cs2pr

      # Composer
      - name: Validate composer.json and composer.lock
        run: COMPOSER=composer-dev.json composer validate

      - name: Get composer cache directory
        run: echo "composer-cache-dir=$(composer config cache-files-dir)" >> $GITHUB_ENV

        # https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows
      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.composer-cache-dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer Dependencies
        run: COMPOSER=composer-dev.json composer install --no-progress --optimize-autoloader

      - name: PHPCS check pull_request
        if: ${{ github.event_name == 'pull_request' }}
        run: ./vendor/bin/phpcs --standard=phpcs.xml ./ -q --report=checkstyle | cs2pr

      - name: PHPCS check workflow_dispatch
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
        run: composer phpcs -- --colors
